# Generated automatically from Makefile.in by configure.
NAME=				xwing
DEPTH=				..

MYLIBS+=			-lawt

##################################################

include $(DEPTH)/all.mk

##################################################

