# Generated automatically from Makefile.in by configure.
NAME			=	awt
DEPTH			=	..

##################################################

include $(DEPTH)/all.mk

##################################################

